'use client';

import { useEffect, useRef, useState } from 'react';
import { WebContainer } from '@webcontainer/api';
import { starterFiles } from '../utils/files';

// Keep this outside the component so it persists across re-renders
let webcontainerInstance: WebContainer;

export default function CodeEnvironment() {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [isBooted, setIsBooted] = useState(false);
  const [previewUrl, setPreviewUrl] = useState('');
  const [logs, setLogs] = useState<string[]>([]);

  useEffect(() => {
    async function bootEnvironment() {
      if (!webcontainerInstance) {
        // 1. Boot the container
        // Must match the page's COEP header (see next.config.ts).
        webcontainerInstance = await WebContainer.boot({ coep: 'credentialless' });
        setIsBooted(true);
        
        // 2. Mount the files generated by your AI
        await webcontainerInstance.mount(starterFiles);

        // 3. Run `npm install`
        setLogs(prev => [...prev, 'Running npm install...']);
        const installProcess = await webcontainerInstance.spawn('npm', ['install']);
        
        // Listen to install logs
        installProcess.output.pipeTo(new WritableStream({
          write(data) {
            setLogs(prev => [...prev, data]);
          }
        }));

        const installExitCode = await installProcess.exit;
        
        if (installExitCode !== 0) {
          throw new Error('Installation failed');
        }

       // 4. Run the Expo Web Server (Replacing `npm run dev`)
        setLogs(prev => [...prev, 'Starting Expo web server...']);
        
        // Ensure the worker spawns the web version of Expo
        await webcontainerInstance.spawn('npx', ['expo', 'start', '--web']);

        // 5. Listen for the "server-ready" event to get the localhost URL
        webcontainerInstance.on('server-ready', (port, url) => {
          setLogs(prev => [...prev, `Server ready at ${url}`]);
          setPreviewUrl(url);
        });
      }
    }

    bootEnvironment();
  }, []);

  return (
    <div className="flex h-screen bg-gray-900 text-white">
      {/* Code Editor / Terminal Panel */}
      <div className="w-1/2 p-4 border-r border-gray-700 flex flex-col">
        <h2 className="text-xl font-bold mb-4">Terminal Logs</h2>
        <div className="flex-1 bg-black p-4 rounded overflow-y-auto font-mono text-sm text-green-400">
          {!isBooted && <p>Booting WebContainer environment...</p>}
          {logs.map((log, i) => (
            <div key={i}>{log}</div>
          ))}
        </div>
      </div>

      {/* Preview Panel */}
      <div className="w-1/2 bg-white flex flex-col">
        {previewUrl ? (
          <iframe 
            src={previewUrl}
            className="w-full h-full border-none"
            title="App Preview"
            allow="cross-origin-isolated"
          />
        ) : (
          <div className="flex-1 flex items-center justify-center text-black">
            Loading Preview...
          </div>
        )}
      </div>
    </div>
  );
}